//
//  CPU-M
//
//  (c) 2025 TDolphin
//

#include "GPUSpec.hpp"

// data info resources:
// https://vgamuseum.info
// https://www.techpowerup.com/gpu-specs/
// wikipedia
// product datasheets from manufacturers

namespace DataInfo
{
    const std::map<GPUID, GPUSpec> gpu2spec {
        { GPUID::_3dfx_Avenger, { ManufacturerID::_3DFX, 1999, std::nullopt, TechnologyID::nm_250, { std::nullopt, 1, 0, 2, 1 }, 15 } },
        { GPUID::_3dfx_VSA_100, { ManufacturerID::_3DFX, 2000, std::nullopt, TechnologyID::nm_250, { std::nullopt, 2, 0, 2, 2 }, 60 } },
        { GPUID::_3DLabs_Permedia_2,
          { ManufacturerID::_3DLABS,
            1997,
            std::nullopt,
            TechnologyID::nm_350,
            { std::nullopt, std::nullopt, std::nullopt, 1, 1 },
            std::nullopt } },
        { GPUID::_3DLabs_Permedia_2V,
          { ManufacturerID::_3DLABS,
            1998,
            std::nullopt,
            TechnologyID::Unknown,
            { std::nullopt, std::nullopt, std::nullopt, 1, 1 },
            std::nullopt } },
        { GPUID::SiS_6326,
          { ManufacturerID::SIS, 1997, ArchitectureID::SiS_1st_Gen, TechnologyID::nm_350, { std::nullopt, 1, 0, 1, 1 }, std::nullopt } },
        { GPUID::SiS_300,
          { ManufacturerID::SIS, 1999, ArchitectureID::SiS_2nd_Gen, TechnologyID::nm_250, { std::nullopt, 1, 0, 1, 1 }, std::nullopt } },
        { GPUID::SiS_305,
          { ManufacturerID::SIS, 2000, ArchitectureID::SiS_2nd_Gen, TechnologyID::nm_150, { std::nullopt, 1, 0, 1, 1 }, std::nullopt } },
        { GPUID::SiS_Mirage_315,
          { ManufacturerID::SIS, 2000, ArchitectureID::SiS_2nd_Gen, TechnologyID::nm_150, { std::nullopt, 2, 0, 4, 2 }, std::nullopt } },
        { GPUID::XGI_XG40,
          { ManufacturerID::XGI, 2003, ArchitectureID::XG4, TechnologyID::nm_130, { std::nullopt, 4, 2, 8, 4 }, std::nullopt } },
        { GPUID::XGI_XG41,
          { ManufacturerID::XGI, 2003, ArchitectureID::XG4, TechnologyID::nm_130, { std::nullopt, 2, 2, 4, 2 }, std::nullopt } },
        { GPUID::XGI_XG42,
          { ManufacturerID::XGI, 2003, ArchitectureID::XG4, TechnologyID::nm_130, { std::nullopt, 2, 1, 4, 2 }, std::nullopt } },
        { GPUID::ATI_Rage_128_Pro,
          { ManufacturerID::ATI, 1999, ArchitectureID::ATI_RAGE_4, TechnologyID::nm_250, { std::nullopt, 2, 0, 2, 2 }, std::nullopt } },
        { GPUID::ATI_R200,
          { ManufacturerID::ATI, 2001, ArchitectureID::ATI_RAGE_7, TechnologyID::nm_150, { std::nullopt, 4, 2, 8, 4 }, 92 } },
        { GPUID::ATI_RV200,
          { ManufacturerID::ATI, 2001, ArchitectureID::ATI_RAGE_7, TechnologyID::nm_150, { std::nullopt, 2, 1, 6, 2 }, 23 } },
        { GPUID::ATI_RV280,
          { ManufacturerID::ATI, 2003, ArchitectureID::ATI_RAGE_7, TechnologyID::nm_150, { std::nullopt, 4, 1, 4, 4 }, 28 } },
        { GPUID::ATI_R350,
          { ManufacturerID::ATI, 2003, ArchitectureID::ATI_R300, TechnologyID::nm_150, { std::nullopt, 8, 4, 8, 8 }, 94 } },
        { GPUID::ATI_RV350,
          { ManufacturerID::ATI, 2003, ArchitectureID::ATI_R300, TechnologyID::nm_130, { std::nullopt, 4, 2, 4, 4 }, 24 } },
        { GPUID::ATI_RV360,
          { ManufacturerID::ATI, 2003, ArchitectureID::ATI_R300, TechnologyID::nm_130, { std::nullopt, 4, 2, 4, 4 }, 24 } },
        { GPUID::ATI_RV380,
          { ManufacturerID::ATI, 2004, ArchitectureID::ATI_R300, TechnologyID::nm_130, { std::nullopt, 4, 2, 4, 4 }, 46 } },
        { GPUID::ATI_RV535,
          { ManufacturerID::ATI, 2006, ArchitectureID::ATI_Ultra_Threaded_SE, TechnologyID::nm_80, { std::nullopt, 12, 5, 4, 4 }, 44 } },
        { GPUID::ATI_RV570,
          { ManufacturerID::ATI, 2006, ArchitectureID::ATI_Ultra_Threaded_SE, TechnologyID::nm_80, { std::nullopt, 36, 8, 12, 12 }, 130 } },
        { GPUID::ATI_R580_PLUS,
          { ManufacturerID::ATI, 2006, ArchitectureID::ATI_Ultra_Threaded_SE, TechnologyID::nm_90, { std::nullopt, 48, 8, 16, 16 }, 125 } },
        { GPUID::ATI_RV620,
          { ManufacturerID::ATI,
            2007,
            ArchitectureID::AMD_TeraScale,
            TechnologyID::nm_55,
            { 40, std::nullopt, std::nullopt, 4, 4, 2 },
            50 } },
        { GPUID::ATI_RV670,
          { ManufacturerID::ATI,
            2008,
            ArchitectureID::AMD_TeraScale,
            TechnologyID::nm_55,
            { 320, std::nullopt, std::nullopt, 16, 16, 4 },
            145 } },
        { GPUID::ATI_RV730,
          { ManufacturerID::ATI,
            2008,
            ArchitectureID::AMD_TeraScale,
            TechnologyID::nm_55,
            { 320, std::nullopt, std::nullopt, 32, 8, 4 },
            118 } },
        { GPUID::AMD_BARTS,
          { ManufacturerID::AMD,
            2010,
            ArchitectureID::AMD_TeraScale_2,
            TechnologyID::nm_40,
            { 1120, std::nullopt, std::nullopt, 56, 32, 14 },
            300 } },
        { GPUID::AMD_CAICOS,
          { ManufacturerID::AMD,
            2011,
            ArchitectureID::AMD_TeraScale_2,
            TechnologyID::nm_40,
            { 160, std::nullopt, std::nullopt, 8, 4, 2 },
            35 } },
        { GPUID::AMD_TURKS,
          { ManufacturerID::AMD,
            2011,
            ArchitectureID::AMD_TeraScale_2,
            TechnologyID::nm_40,
            { 480, std::nullopt, std::nullopt, 24, 8, 6 },
            75 } },
        { GPUID::AMD_BAFFIN,
          { ManufacturerID::AMD,
            2016,
            ArchitectureID::AMD_GCN_4_0,
            TechnologyID::nm_14,
            { 1024, std::nullopt, std::nullopt, 64, 16, 16 },
            80 } },
        { GPUID::ATI_M10,
          { ManufacturerID::ATI, 2003, ArchitectureID::ATI_R300, TechnologyID::nm_130, { std::nullopt, 4, 2, 4, 4 }, std::nullopt } },
        { GPUID::ATI_M11,
          { ManufacturerID::ATI, 2003, ArchitectureID::ATI_R300, TechnologyID::nm_130, { std::nullopt, 4, 2, 4, 4 }, std::nullopt } },
        { GPUID::ATI_M12,
          { ManufacturerID::ATI, 2004, ArchitectureID::ATI_R300, TechnologyID::nm_130, { std::nullopt, 4, 2, 4, 4 }, std::nullopt } },
    };
}
