//
//  CPU-M
//
//  (c) 2025 TDolphin
//

#include "HardwareSystemSpec.hpp"

// sources:
// Pegasos book, Efika book, wikipedia, https://support.apple.com

namespace DataInfo
{
    const std::map<std::string, HardwareSystemSpec> hardwareSystem2spec {
        {
            "bplan,Pegasos",
            {
                std::nullopt,
                "Genesi Pegasos",
                2003,
                2003,
                "CPU card",
                "3.5\"",
                "IDE ATA 100",
                "Smart Firmware",
                { { "PC133 SDRAM DIMM", "133 MHz", 2048, 2 } },
                { { "USB 1.1", 3 },
                  { "FireWire 400", 3 },
                  { "Ethernet 10/100 Mbps", 1 },
                  { "Audio In/Out", 1 },
                  { "Serial RS232", 1 },
                  { "PS/2 keyboard", 1 },
                  { "PS/2 mouse", 1 },
                  { "Parallel", 1 } },
                std::nullopt,
                "Northbridge: Mai Logic Articia S",
            },
        },
        {
            "bplan,Pegasos2",
            {
                std::nullopt,
                "Genesi Pegasos 2",
                2003,
                2006,
                "CPU card",
                "3.5\"",
                "IDE ATA 100",
                "Smart Firmware",
                { { "PC-2100 DDR SDRAM", "133 MHz", 8192, 2 } },
                { { "USB 1.1", 3 },
                  { "FireWire 400", 3 },
                  { "Ethernet 10/100 Mbps", 1 },
                  { "Ethernet 1000 Mbps", 1 },
                  { "Audio In/Out", 1 },
                  { "Serial RS232", 1 },
                  { "PS/2 keyboard", 1 },
                  { "PS/2 mouse", 1 },
                  { "Parallel", 1 } },
                std::nullopt,
                "Northbridge: Marvell Discovery II MV64361",
            },
        },
        {
            "bplan,EFIKA5K2",
            {
                std::nullopt,
                "Genesi Efika 5200B",
                2006,
                2007,
                "Soldered",
                "2.5\"",
                "PATA",
                "Smart Firmware",
                { { "DDR SDRAM", "266 MHz", 128, 0 } },
                { { "USB 1.1", 2 }, { "Optical Audio", 1 }, { "Ethernet 10/100 Mbps", 1 }, { "Audio In/Out", 1 }, { "Serial RS232", 1 } },
                "Memory is soldered to the motherboard",
                std::nullopt,
            },
        },
        {
            "Sam460ex",
            {
                std::nullopt,
                "ACube Sam460ex",
                2010,
                2015,
                "Soldered",
                "--",
                "SATA 2.0",
                "U-Boot",
                { { "PC2-3200 DDR2 SDRAM", "400 MHz", 2048, 1 } },
                { { "USB 2.0", 6 }, { "USB 1.1", 1 }, { "Ethernet 10/100/1000 Mbps", 2 }, { "Audio In/Out", 1 }, { "Serial RS232", 1 } },
                "recommended PC2-5200/6400 DDR2 (533 MHz / 667 MHz) modules",
                std::nullopt,
            },
        },
        {
            "Sam460cr",
            {
                std::nullopt,
                "ACube Sam460cr",
                2015,
                2021,
                "Soldered",
                "--",
                "--",
                "U-Boot",
                { { "PC2-3200 DDR2 SDRAM", "400 MHz", 2048, 1 } },
                { { "USB 2.0", 6 }, { "Ethernet 10/100/1000 Mbps", 2 }, { "Serial RS232", 1 } },
                "recommended PC2-5200/6400 DDR2 (533 MHz / 667 MHz) modules",
                std::nullopt,
            },
        },
        {
            "CyrusPlus",
            {
                std::nullopt,
                "AmigaOne X5000",
                2016,
                2022,
                "Soldered",
                "--",
                "SATA 2.0",
                "Smart Firmware",
                { { "DDR3 SDRAM", "1333/1600 MHz", 16384, 2 } },
                { { "USB 2.0", 8 }, { "Ethernet 10/100/1000 Mbps", 1 }, { "Serial RS232", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "Mirari",
            {
                std::nullopt,
                "Harald (Geennaam) Mirari",
                2017,
                2021,
                "Soldered",
                "--",
                "SATA, NVMe",
                "U-Boot",
                { { "DDR3 SDRAM 1.35V", "?? MHz", 8192, 1 } },
                { { "USB 2.0", 6 },
                  { "USB 3.2", 3 },
                  { "Ethernet 10/100/1000 Mbps", 1 },
                  { "Serial RS232", 1 },
                  { "Audio In/Out", 1 },
                  { "Optical Audio", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac3,1",
            {
                "M5183",
                "Apple Power Mac G4",
                1999,
                2000,
                "custom 300-pin daughtercard",
                "3.5\"",
                "Ultra ATA/66",
                "Open Firmware",
                { { "PC100 SDRAM", "333 MHz", 2048, 4 } },
                { { "USB 1.1", 2 }, { "FireWire 400", 3 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac10,1",
            {
                "A1103",
                "Apple Mac mini G4",
                2005,
                2006,
                "Soldered",
                "2.5\"",
                "Ultra ATA/100",
                "Open Firmware",
                { { "PC2700 DDR SDRAM", "333 MHz", 1024, 1 } },
                { { "USB 2.0", 2 }, { "FireWire 400", 1 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac10,2",
            {
                "A1103",
                "Apple Mac mini G4",
                2005,
                2006,
                "Soldered",
                "2.5\"",
                "Ultra ATA/100",
                "Open Firmware",
                { { "PC2700 DDR SDRAM", "333 MHz", 1024, 1 } },
                { { "USB 2.0", 2 }, { "FireWire 400", 1 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerBook6,7",
            {
                "A1133 (12\") or A1134 (14\")",
                "Apple iBook G4 (12\" or 14\")",
                2005,
                2006,
                "Soldered",
                "2.5\"",
                "Ultra ATA/100",
                "Open Firmware",
                { { "PC2700 DDR SDRAM", "333 MHz", 1536, 1 } }, // 1.5 GB RAM max, 1 slot
                { { "USB 2.0", 2 }, { "FireWire 400", 1 }, { "Ethernet 10/100 Mbps", 1 } },
                "512 MB of 333 MHz PC2700 DDR SDRAM (soldered to logic board)",
                std::nullopt,
            },
        },
        {
            "PowerMac7,3",
            {
                "A1047",
                "Apple Power Macintosch G5",
                2004,
                2005,
                "G5 Daughtercard",
                "3.5\"",
                "Serial ATA",
                "Open Firmware",
                { { "PC3200 DDR", "400 MHz", 4096, 4 }, { "PC3200 DDR", "400 MHz", 8192, 8 } }, // 4 or 8 GB max, 4 or 8 slots
                { { "USB 2.0", 3 }, { "FireWire 400", 2 }, { "FireWire 800", 1 }, { "Ethernet 10/100/1000 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac5,1",
            {
                "M7886",
                "Apple Power Macintosh G4 Cube",
                2000,
                2001,
                "G4 Daughtercard",
                "3.5\"",
                "Ultra ATA/66",
                "Open Firmware",
                { { "PC100 SDRAM", "100 MHz", 1536, 3 } },
                { { "USB 1.1", 2 }, { "FireWire 400", 2 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac7,3",
            {
                "A1144 or A1145",
                "Apple iMac G5 17\" or 20\") (iSight)",
                2005,
                2006,
                "Soldered",
                "3.5\"",
                "Serial ATA",
                "Open Firmware",
                { { "PC2-4200 DDR2", "533 MHz", 4608, 1 } },
                { { "USB 2.0", 3 }, { "FireWire 400", 2 }, { "Ethernet 10/100/1000 Mbps", 1 } },
                "512 MB of 533 MHz DDR2 SDRAM (soldered to logic board)",
                std::nullopt,
            },
        },
    };
}
