//
//  CPU-M
//
//  (c) 2025 TDolphin
//

#include "HardwareSystemSpec.hpp"

// sources:
// Pegasos book, Efika book, wikipedia, https://support.apple.com

namespace DataInfo
{
    const std::map<std::string, HardwareSystemSpec> hardwareSystem2spec {
        {
            "bplan,Pegasos",
            {
                std::nullopt,
                "Genesi Pegasos",
                2003,
                2003,
                "CPU card",
                { "IDE ATA 100 (3.5\")" },
                "Smart Firmware",
                std::nullopt,
                { { "PC133 SDRAM DIMM", "133 MHz", 2048, 2 } },
                { { "USB 1.1", 3 },
                  { "FireWire 400", 3 },
                  { "Ethernet 10/100 Mbps", 1 },
                  { "Audio In/Out", 1 },
                  { "Serial RS232", 1 },
                  { "PS/2 keyboard", 1 },
                  { "PS/2 mouse", 1 },
                  { "Parallel", 1 } },
                std::nullopt,
                "Northbridge: Mai Logic Articia S",
            },
        },
        {
            "bplan,Pegasos2",
            {
                std::nullopt,
                "Genesi Pegasos 2",
                2003,
                2006,
                "CPU card",
                { "IDE ATA 100 (3.5\")" },
                "Smart Firmware",
                std::nullopt,
                { { "PC-2100 DDR SDRAM", "133 MHz", 8192, 2 } },
                { { "USB 1.1", 3 },
                  { "FireWire 400", 3 },
                  { "Ethernet 10/100 Mbps", 1 },
                  { "Ethernet 1000 Mbps", 1 },
                  { "Audio In/Out", 1 },
                  { "Serial RS232", 1 },
                  { "PS/2 keyboard", 1 },
                  { "PS/2 mouse", 1 },
                  { "Parallel", 1 } },
                std::nullopt,
                "Northbridge: Marvell Discovery II MV64361",
            },
        },
        {
            "bplan,EFIKA5K2",
            {
                std::nullopt,
                "Genesi Efika 5200B",
                2006,
                2007,
                "Soldered",
                { "PATA (2.5\")" },
                "Smart Firmware",
                { { "DDR SDRAM", "266 MHz", 128 } },
                {},
                { { "USB 1.1", 2 }, { "Optical Audio", 1 }, { "Ethernet 10/100 Mbps", 1 }, { "Audio In/Out", 1 }, { "Serial RS232", 1 } },
                "Memory is soldered to the mainboard, no slots available",
                std::nullopt,
            },
        },
        {
            "Sam460ex",
            {
                std::nullopt,
                "ACube Sam460ex",
                2010,
                2015,
                "Soldered",
                { "SATA 2.0" },
                "U-Boot",
                std::nullopt,
                { { "PC2-3200 DDR2 SDRAM", "400 MHz", 2048, 1 } },
                { { "USB 2.0", 6 }, { "USB 1.1", 1 }, { "Ethernet 10/100/1000 Mbps", 2 }, { "Audio In/Out", 1 }, { "Serial RS232", 1 } },
                "recommended PC2-5200/6400 DDR2 (533 MHz / 667 MHz) modules",
                std::nullopt,
            },
        },
        {
            "Sam460cr",
            {
                std::nullopt,
                "ACube Sam460cr",
                2015,
                2021,
                "Soldered",
                {},
                "U-Boot",
                std::nullopt,
                { { "PC2-3200 DDR2 SDRAM", "400 MHz", 2048, 1 } },
                { { "USB 2.0", 6 }, { "Ethernet 10/100/1000 Mbps", 2 }, { "Serial RS232", 1 } },
                "recommended PC2-5200/6400 DDR2 (533 MHz / 667 MHz) modules",
                std::nullopt,
            },
        },
        {
            "CyrusPlus",
            {
                std::nullopt,
                "AmigaOne X5000",
                2016,
                2022,
                "Soldered",
                { "SATA 2.0" },
                "Smart Firmware",
                std::nullopt,
                { { "PC3-10600/12800 DDR3 SDRAM", "1333/1600 MHz", 16384, 2 } },
                { { "USB 2.0", 8 }, { "Ethernet 10/100/1000 Mbps", 1 }, { "Serial RS232", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "Mirari",
            {
                std::nullopt,
                "Harald's Mirari",
                2025,
                std::nullopt,
                "Soldered",
                { "SATA", "NVMe", "MicroSD" },
                "U-Boot",
                std::nullopt,
                { { "PC3-12800 DDR3 SDRAM 1.35V", "1600 MHz", 8192, 1 } },
                { { "USB 2.0", 6 },
                  { "USB 3.2", 3 },
                  { "Ethernet 10/100/1000 Mbps", 1 },
                  { "Serial RS232", 1 },
                  { "Audio In/Out", 1 },
                  { "Optical Audio", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac3,1",
            {
                "M5183",
                "Apple Power Mac G4",
                1999,
                2000,
                "custom 300-pin daughtercard",
                { "Ultra ATA/66 (3.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC100 SDRAM", "333 MHz", 2048, 4 } },
                { { "USB 1.1", 2 }, { "FireWire 400", 3 }, { "Ethernet 10/100 Mbps", 1 }, { "Modem 56k", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac5,1",
            {
                "M7886",
                "Apple Power Macintosh G4 Cube",
                2000,
                2001,
                "G4 Daughtercard",
                { "Ultra ATA/66 (3.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC100 SDRAM", "100 MHz", 1536, 3 } },
                { { "USB 1.1", 2 }, { "FireWire 400", 2 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerBook5,6",
            {
                "A1106",
                "Apple PowerBook G4 (15\")",
                2005,
                2005,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC-2700 DDR SDRAM", "333 MHz", 2048, 2 } }, // 2 GB RAM max, 1 slot
                {
                    { "USB 2.0", 2 },
                    { "FireWire 400", 1 },
                    { "FireWire 800", 1 },
                    { "Ethernet 10/100/1000 Mbps", 1 },
                    { "Type I/II PC Card", 1 },
                    { "Modem 56k", 1 },
                    { "Audio In", 1 },
                    { "Audio Out (3.5mm Headphone Jack)", 1 },
                    { "DVI", 1 },
                    { "S-Video", 1 },
                },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerBook5,7",
            {
                "A1107",
                "Apple PowerBook G4 (17\")",
                2005,
                2005,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC-2700 DDR SDRAM", "333 MHz", 2048, 2 } }, // 2 GB RAM max, 2 slots
                {
                    { "USB 2.0", 2 },
                    { "FireWire 400", 1 },
                    { "FireWire 800", 1 },
                    { "Ethernet 10/100/1000 Mbps", 1 },
                    { "Type I/II PC Card", 1 },
                    { "Modem 56k", 1 },
                    { "Audio In", 1 },
                    { "Audio Out (3.5mm Headphone Jack)", 1 },
                    { "DVI", 1 },
                    { "S-Video", 1 },
                },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerBook5,8",
            {
                "A1138",
                "Apple PowerBook G4 (15\")",
                2005,
                2006,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC2-4200 DDR2 SDRAM", "333 MHz", 2048, 2 } }, // 2 GB RAM max, 2 slots
                {
                    { "USB 2.0", 2 },
                    { "FireWire 400", 1 },
                    { "FireWire 800", 1 },
                    { "Ethernet 10/100/1000 Mbps", 1 },
                    { "Type I/II PC Card", 1 },
                    { "Modem 56k", 1 },
                    { "Audio In", 1 },
                    { "Audio Out (3.5mm Headphone Jack)", 1 },
                    { "DVI", 1 },
                    { "S-Video", 1 },
                },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerBook5,9",
            {
                "A1139",
                "Apple PowerBook G4 (17\")",
                2005,
                2006,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC2-4200 DDR2 SDRAM", "333 MHz", 2048, 2 } }, // 2 GB RAM max, 2 slots
                {
                    { "USB 2.0", 2 },
                    { "FireWire 400", 1 },
                    { "FireWire 800", 1 },
                    { "Ethernet 10/100/1000 Mbps", 1 },
                    { "Type I/II PC Card", 1 },
                    { "Modem 56k", 1 },
                    { "Audio In", 1 },
                    { "Audio Out (3.5mm Headphone Jack)", 1 },
                    { "DVI", 1 },
                    { "S-Video", 1 },
                },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerBook6,7",
            {
                "A1133 (12\") or A1134 (14\")",
                "Apple iBook G4 (12\" or 14\")",
                2005,
                2006,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                { { "DDR SDRAM", "333 MHz", 512 } }, // 512 MB soldered
                { { "PC-2700 DDR SDRAM", "333 MHz", 1024, 1 } }, // 1 GB RAM max, 1 slot
                {
                    { "USB 2.0", 2 },
                    { "FireWire 400", 1 },
                    { "Ethernet 10/100 Mbps", 1 },
                    { "Modem 56k", 1 },
                    { "Mini VGA", 1 },
                    { "Audio Out (3.5mm Headphone Jack)", 1 },
                },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac7,3",
            {
                "A1047",
                "Apple Power Macintosch G5",
                2004,
                2005,
                "G5 Daughtercard",
                { "SATA" },
                "Open Firmware",
                std::nullopt,
                { { "PC-3200 DDR", "400 MHz", 4096, 4 }, { "PC-3200 DDR", "400 MHz", 8192, 8 } }, // 4 or 8 GB max, 4 or 8 slots
                { { "USB 2.0", 3 }, { "FireWire 400", 2 }, { "FireWire 800", 1 }, { "Ethernet 10/100/1000 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac10,1",
            {
                "A1103",
                "Apple Mac mini G4",
                2005,
                2006,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC-2700 DDR SDRAM", "333 MHz", 1024, 1 } },
                { { "USB 2.0", 2 }, { "FireWire 400", 1 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac10,2",
            {
                "A1103",
                "Apple Mac mini G4",
                2005,
                2006,
                "Soldered",
                { "Ultra ATA/100 (2.5\")" },
                "Open Firmware",
                std::nullopt,
                { { "PC-2700 DDR SDRAM", "333 MHz", 1024, 1 } },
                { { "USB 2.0", 2 }, { "FireWire 400", 1 }, { "Ethernet 10/100 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac11,2",
            {
                "A1117 or A1177",
                "Apple Power Macintosh G5 Dual or Quad Core",
                2005,
                2006,
                "G5 Daughtercard",
                { "SATA" },
                "Open Firmware",
                std::nullopt,
                { { "PC2-4200 DDR2", "533 MHz", 16384, 8 } },
                { { "USB 2.0", 4 }, { "FireWire 400", 2 }, { "FireWire 800", 1 }, { "Ethernet 10/100/1000 Mbps", 2 } },
                std::nullopt,
                std::nullopt,
            },
        },
        {
            "PowerMac12,1",
            {
                "A1144 or A1145",
                "Apple iMac G5 17\" or 20\") (iSight)",
                2005,
                2006,
                "Soldered",
                { "SATA" },
                "Open Firmware",
                { { "DDR2 SDRAM", "533 MHz", 512 } }, // 512 MB soldered
                { { "PC2-4200 DDR2", "533 MHz", 4096, 1 } },
                { { "USB 2.0", 3 }, { "FireWire 400", 2 }, { "Ethernet 10/100/1000 Mbps", 1 } },
                std::nullopt,
                std::nullopt,
            },
        },
    };
}
